import type { Route } from "./App";

export const DATA: Route[] = [
    {
        method: "GET|HEAD",
        uri: "/",
        name: "home",
        action: "Closure",
        middleware: ["web", "auth", "verified"],
    },
    {
        method: "GET|HEAD",
        uri: "documentaciones",
        name: "document.index",
        action: "App\\Http\\Controllers\\DocumentController@index",
        middleware: ["web", "auth", "verified"],
    },
    {
        method: "GET|HEAD",
        uri: "documentaciones/crear",
        name: "document.create",
        action: "App\\Http\\Controllers\\DocumentController@create",
        middleware: ["web", "auth", "verified"],
    },
    {
        method: "POST",
        uri: "documentaciones/crear",
        name: "document.store",
        action: "App\\Http\\Controllers\\DocumentController@store",
        middleware: ["web", "auth", "verified"],
    },
    {
        method: "GET|HEAD",
        uri: "documentaciones/{document}/editar",
        name: "document.edit",
        action: "App\\Http\\Controllers\\DocumentController@edit",
        middleware: ["web", "auth", "verified"],
    },
    {
        method: "PUT",
        uri: "documentaciones/{document}/editar",
        name: "document.update",
        action: "App\\Http\\Controllers\\DocumentController@update",
        middleware: ["web", "auth", "verified"],
    },
    {
        method: "DELETE",
        uri: "documentaciones/{document}/eliminar",
        name: "document.delete",
        action: "App\\Http\\Controllers\\DocumentController@destroy",
        middleware: ["web", "auth", "verified"],
    },
    {
        method: "GET|HEAD",
        uri: "documentaciones/{document}/ver",
        name: "document.show",
        action: "App\\Http\\Controllers\\DocumentController@show",
        middleware: ["web", "auth", "verified"],
    },
    {
        method: "GET|HEAD",
        uri: "login",
        name: "login",
        action:
            "App\\Http\\Controllers\\Auth\\AuthenticatedSessionController@create",
        middleware: ["web", "guest"],
    },
    {
        method: "POST",
        uri: "login",
        name: null,
        action:
            "App\\Http\\Controllers\\Auth\\AuthenticatedSessionController@store",
        middleware: ["web", "guest"],
    },
    {
        method: "POST",
        uri: "logout",
        name: "logout",
        action:
            "App\\Http\\Controllers\\Auth\\AuthenticatedSessionController@destroy",
        middleware: ["web", "auth"],
    },
    {
        method: "GET|HEAD",
        uri: "proyectos",
        name: "projects.index",
        action: "Closure",
        middleware: ["web", "auth", "verified"],
    },
    {
        method: "POST",
        uri: "proyectos",
        name: "projects.store",
        action: "App\\Http\\Controllers\\ProjectController@store",
        middleware: ["web", "auth", "verified"],
    },
    {
        method: "DELETE",
        uri: "proyectos/{project}",
        name: "projects.destroy",
        action: "App\\Http\\Controllers\\ProjectController@destroy",
        middleware: ["web", "auth", "verified"],
    },
    {
        method: "GET|HEAD",
        uri: "proyectos/{project}/descargar",
        name: "projects.download",
        action: "App\\Http\\Controllers\\ProjectController@downloadProject",
        middleware: ["web", "auth", "verified"],
    },
    {
        method: "GET|HEAD",
        uri: "proyectos/{project}/descargar-db",
        name: "projects.download.database",
        action: "App\\Http\\Controllers\\ProjectController@downloadDatabase",
        middleware: ["web", "auth", "verified"],
    },
    {
        method: "GET|HEAD",
        uri: "seo-check",
        name: "seo.index",
        action: "App\\Http\\Controllers\\SeoCheckerController@index",
        middleware: ["web", "auth", "verified"],
    },
    {
        method: "POST",
        uri: "seo-check",
        name: "seo.analyze",
        action: "App\\Http\\Controllers\\SeoCheckerController@analyzeUrl",
        middleware: ["web", "auth", "verified"],
    },
    {
        method: "GET|HEAD|POST|PUT|PATCH|DELETE|OPTIONS",
        uri: "settings",
        name: null,
        action: "Illuminate\\Routing\\RedirectController",
        middleware: ["web", "auth"],
    },
    {
        method: "GET|HEAD",
        uri: "settings/appearance",
        name: "appearance",
        action: "Closure",
        middleware: ["web", "auth"],
    },
    {
        method: "GET|HEAD",
        uri: "settings/password",
        name: "password.edit",
        action: "App\\Http\\Controllers\\Settings\\PasswordController@edit",
        middleware: ["web", "auth"],
    },
    {
        method: "PUT",
        uri: "settings/password",
        name: "password.update",
        action: "App\\Http\\Controllers\\Settings\\PasswordController@update",
        middleware: ["web", "auth"],
    },
    {
        method: "GET|HEAD",
        uri: "settings/profile",
        name: "profile.edit",
        action: "App\\Http\\Controllers\\Settings\\ProfileController@edit",
        middleware: ["web", "auth"],
    },
    {
        method: "PATCH",
        uri: "settings/profile",
        name: "profile.update",
        action: "App\\Http\\Controllers\\Settings\\ProfileController@update",
        middleware: ["web", "auth"],
    },
    {
        method: "DELETE",
        uri: "settings/profile",
        name: "profile.destroy",
        action: "App\\Http\\Controllers\\Settings\\ProfileController@destroy",
        middleware: ["web", "auth"],
    },
    {
        method: "GET|HEAD",
        uri: "storage/{path}",
        name: "storage.local",
        action: "Closure",
        middleware: [],
    },
    {
        method: "GET|HEAD",
        uri: "up",
        name: null,
        action: "Closure",
        middleware: [],
    },
];
